# Philadelphia Night
thm_bg="#090c12"
thm_fg="#c8d4e8"
thm_cyan="#60d0f0"
thm_black="#0d1119"
thm_gray="#4a5870"
thm_magenta="#8866dd"
thm_pink="#aa66cc"
thm_red="#cc2828"
thm_green="#30b870"
thm_yellow="#c8a030"
thm_blue="#2a72ff"
thm_orange="#f0a030"
thm_black4="#2d3650"

# ----------------------------=== Theme ===--------------------------

# status
set -g status-interval 1
set -g escape-time 10
set -g focus-events on
set -g status "on"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"
set-option -g status-style bg=default

# messages
set -g message-style fg="${thm_cyan}",bg=default,align="centre"
set -g message-command-style fg="${thm_cyan}",bg=default,align="centre"

# panes
set -g pane-border-style fg="${thm_black4}"
set -g pane-active-border-style fg="${thm_blue}"

# windows
setw -g window-status-activity-style fg="${thm_fg}",bg=default,none
setw -g window-status-separator ""
setw -g window-status-style fg="${thm_gray}",bg=default,none

# statusline
set -g status-left ""
set -g status-right "#{?client_prefix,#[bg=$thm_red],#[bg=$thm_blue]}#[fg=$thm_bg]  #[fg=$thm_fg,bg=default] #S "

# Window colors
setw -g window-status-format "#[fg=$thm_bg,bg=$thm_gray] #I #[fg=$thm_gray,bg=default] #W "
setw -g window-status-current-format "#[fg=$thm_bg,bg=$thm_blue] #I #[fg=$thm_blue,bg=default] #W "

# modes
setw -g clock-mode-colour "${thm_blue}"
setw -g mode-style "fg=${thm_cyan} bg=default bold"
